# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=256, null=True)),
                ('sender', models.CharField(max_length=256, null=True)),
                ('receiver', models.CharField(max_length=256)),
                ('subject', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('attach', models.TextField(null=True)),
                ('mail_type', models.CharField(default='default', max_length=10)),
                ('desc', models.TextField(null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ser_name', models.CharField(max_length=256, null=True)),
                ('ser_user', models.CharField(max_length=256, null=True)),
                ('handler', models.CharField(max_length=256, null=True)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='message.Mail')),
            ],
        ),
    ]
