#coding=utf-8
"""
Django settings for innervm project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!ze1z2^96&*_9cx2jlh+8lcbs2oc60_1wrh2$o0_#8#!z(=h@c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'conf',
    'accounts',
    'message',
    'vmmanager',
    'vmadmin',
    'interclient',
    'i18n',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'i18n.middleware.RequestLanguageMiddleware',    
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + '/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conf.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'


TIME_ZONE = 'PRC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGES = (
    ('en', ('English')),
    ('zh-hans', ('Chinese')),
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
LANGUAGE_COOKIE_TIMEOUT = 9999999
LANGUAGE_COOKIE_NAME = 'innervm_language'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (  
     os.path.join(BASE_DIR, 'static'),  
 )  

#STATIC_ROOT = './static/'

#TEMPLATE_CONTEXT_PROCESSORS=(
#    "django.core.context_processors.request",
#    "django.contrib.auth.context_processors.auth",
#)

EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.cnic.cn'
EMAIL_HOST_USER = 'lzxddz@cnic.cn'
EMAIL_HOST_PASSWORD = 'sdc123456'

ADMINS = (
    ('user', 'user@sample.cn'),
)


# vmmanager settings
VMMANAGER_HOST = '127.0.0.1'
VNC_HOST = 'vm.dcloud.cn'
VMMANAGER_USER = 'test'
VMMANAGER_PASSWORD = 'cnic.cn'

# vmadmin settings
DEFAULT_VM_LIMIT = 3
SETTING_KEY_DEFAULT_VM_LIMIT = 'DEFAULT_VM_LIMIT'
DEFAULT_LOCAL_NET_CODE = 'local'
SETTING_KEY_LOCAL_NET_CODE = 'LOCAL_NET_CODE'
DEFAUTL_CACHE_EXP_TIME = 600
SETTING_KEY_CACHE_EXP_TIME = 'CACHE_EXP_TIME'

CACHE_ENABLE = True
