# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 08:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='Tpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.IntegerField(help_text='个', verbose_name='cpu数')),
                ('mem', models.IntegerField(help_text='MB', verbose_name='内存大小')),
                ('term', models.IntegerField(help_text='月', verbose_name='有效期')),
            ],
            options={
                'verbose_name': '虚拟机性能参数',
                'verbose_name_plural': '虚拟机性能参数',
            },
        ),
        migrations.CreateModel(
            name='Vm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('vmid', models.CharField(max_length=100, unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('cpu', models.IntegerField()),
                ('mem', models.IntegerField()),
                ('image', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ipv4', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '虚拟机',
                'verbose_name_plural': '虚拟机',
            },
        ),
    ]
